[package]
name = "pharaoh-rs"
version = "0.1.0"
edition = "2021"
description = "Simple library to parse word alignments in the Pharaoh format"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
